description: ProtTrans - Species - Single GPU -   
data:
data:
  # Cluster - Avocado
  train_data: /data/ldap/protein_sequences/data/uniprot_swiss-prot_vbh_p100d_w_train.fasta
  val_data: /data/ldap/protein_sequences/data/uniprot_swiss-prot_vbh_p100d_w_val.fasta
  test_data: /data/ldap/protein_sequences/data/uniprot_swiss-prot_vbh_p100d_w_test.fasta
  pretrained_path: /data/ldap/protein_sequences/original_read_only/models/prot-trans_bert
  voc_path: /data/ldap/protein_sequences/original_read_only/models/prot-trans_bert/vocab.txt
  worker: 64
hyperparameters:
  global_batch_size: 16
  classification_feature: 512
  classification_dropout: 0.1
  classification_lr: 2e-3
  bert_lr: 5e-5
  bert_freeze: false
  sequence_length: 102 # +2 for CLS and SEP Tokens
# Single run without hyperparameter tuning
searcher:
  name: single
  metric: val_acc
  smaller_is_better: false
  max_length:
    # 35592 sequences and batch_size 16 -> 2240 batches per epoch -> 10 epochs = 22400 batches
    batches: 4480
min_validation_period:
  batches: 2240
resources:
  agent_label: pepper-cluster
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 0
  save_experiment_best: 0
# Docker container used
environment:
  image:
    cpu: "deepprojects/determined-pytorch-1.6-tf-2.2-cpu"
    gpu: "deepprojects/determined-cuda-10.1-pytorch-1.6-tf-2.2-gpu"
# Bind Avocado into the docker container
bind_mounts:
 - host_path: /data/ldap
   container_path: /data/ldap
   read_only: true
entrypoint: trails:SpeciesClassification
